export interface ICpuConfig {
  id: number;
  name: string;
  vendor: 'general' | 'apple';
  shortName: string;
  multiplier: number;
  tier: 'Medium 1' | 'Low 2' | 'Low 1' | 'Medium 2';
  sp: number;
  fn: number;
  fizzCpuPricePerHour: number;
  fizzCpuPricePerMonth: number;
  fizzRamPricePerGbPerMonth: number;
  fizzStoragePricePerGbPerMonth: number;
}

export const CpuConfig: ICpuConfig[] = [
  {
    id: 1,
    name: 'General Purpose',
    vendor: 'general',
    shortName: 'gp',
    multiplier: 1,
    tier: 'Medium 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.001,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 4,
    name: 'M2 Pro',
    vendor: 'apple',
    shortName: 'm2-pro',
    multiplier: 0.75,
    tier: 'Low 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.056,
    fizzCpuPricePerMonth: 41.14,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 5,
    name: 'M2 Max',
    vendor: 'apple',
    shortName: 'm2-max',
    multiplier: 1,
    tier: 'Medium 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.07,
    fizzCpuPricePerMonth: 51.1,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 6,
    name: 'M3 Max',
    vendor: 'apple',
    shortName: 'm3-max',
    multiplier: 1,
    tier: 'Medium 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.07,
    fizzCpuPricePerMonth: 51.1,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 7,
    name: 'M3 Pro',
    vendor: 'apple',
    shortName: 'm3-pro',
    multiplier: 0.75,
    tier: 'Low 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.062,
    fizzCpuPricePerMonth: 44.64,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 8,
    name: 'M3',
    vendor: 'apple',
    shortName: 'm3',
    multiplier: 0.5,
    tier: 'Low 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.05,
    fizzCpuPricePerMonth: 36.0,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 9,
    name: 'M2',
    vendor: 'apple',
    shortName: 'm2',
    multiplier: 0.5,
    tier: 'Low 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.044,
    fizzCpuPricePerMonth: 31.94,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 10,
    name: 'M2 Ultra',
    vendor: 'apple',
    shortName: 'm2-ultra',
    multiplier: 1.5,
    tier: 'Medium 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.15,
    fizzCpuPricePerMonth: 108.0,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 11,
    name: 'M1',
    vendor: 'apple',
    shortName: 'm1',
    multiplier: 0.5,
    tier: 'Low 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.035,
    fizzCpuPricePerMonth: 25.55,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 12,
    name: 'M1 Max',
    vendor: 'apple',
    shortName: 'm1-max',
    multiplier: 0.75,
    tier: 'Low 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.05,
    fizzCpuPricePerMonth: 36.0,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 13,
    name: 'M1 Pro',
    vendor: 'apple',
    shortName: 'm1-pro',
    multiplier: 0.5,
    tier: 'Low 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.044,
    fizzCpuPricePerMonth: 31.94,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 14,
    name: 'M1 Ultra',
    vendor: 'apple',
    shortName: 'm1-ultra',
    multiplier: 0.75,
    tier: 'Low 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.12,
    fizzCpuPricePerMonth: 86.4,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 15,
    name: 'M4',
    vendor: 'apple',
    shortName: 'm4',
    multiplier: 0.75,
    tier: 'Low 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.062,
    fizzCpuPricePerMonth: 44.64,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 16,
    name: 'M4 Pro',
    vendor: 'apple',
    shortName: 'm4-pro',
    multiplier: 1,
    tier: 'Medium 1',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.074,
    fizzCpuPricePerMonth: 53.28,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
  {
    id: 17,
    name: 'M4 Max',
    vendor: 'apple',
    shortName: 'm4-max',
    multiplier: 1.5,
    tier: 'Medium 2',
    sp: 0.01,
    fn: 25,
    fizzCpuPricePerHour: 0.1,
    fizzCpuPricePerMonth: 72.0,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
  },
];
