export interface IGpuConfig {
  id: number;
  name: string;
  tier:
    | 'Entry 1'
    | 'Entry 2'
    | 'Low 1'
    | 'Low 2'
    | 'Medium 1'
    | 'Medium 2'
    | 'High 1'
    | 'High 2'
    | 'Ultra High 1'
    | 'Ultra High 2'
    | 'Ultra High 3';
  shortName: string;
  multiplier: number;
  baseFnPoints: number;
  fizzGpuPricePerHour: number;
  fizzGpuPricePerMonth: number;
  fizzCpuPricePerMonth: number;
  fizzRamPricePerGbPerMonth: number;
  fizzStoragePricePerGbPerMonth: number;
  vendor: 'nvidia';
}

export const GpuConfig: IGpuConfig[] = [
  {
    id: 1,
    name: 'NVIDIA T1000',
    tier: 'Entry 1',
    shortName: 't1000',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.044,
    fizzGpuPricePerMonth: 31.5,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 2,
    name: 'NVIDIA Tesla p4',
    tier: 'Entry 1',
    shortName: 'p4',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.046,
    fizzGpuPricePerMonth: 32.9,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 3,
    name: 'NVIDIA GTX 1050',
    tier: 'Entry 1',
    shortName: 'gtx1050',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 36,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 4,
    name: 'NVIDIA GTX 1050 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1050ti',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.07,
    fizzGpuPricePerMonth: 50.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 5,
    name: 'NVIDIA GTX 1060',
    tier: 'Entry 1',
    shortName: 'gtx1060',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 36,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 6,
    name: 'NVIDIA GTX 1070',
    tier: 'Entry 1',
    shortName: 'gtx1070',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 36,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 7,
    name: 'NVIDIA GTX 1070 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1070ti',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.07,
    fizzGpuPricePerMonth: 50.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 8,
    name: 'NVIDIA GTX 1080',
    tier: 'Entry 1',
    shortName: 'gtx1080',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.053,
    fizzGpuPricePerMonth: 37.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 9,
    name: 'NVIDIA GTX 1080 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1080ti',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.072,
    fizzGpuPricePerMonth: 51.84,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 10,
    name: 'NVIDIA RTX 2060',
    tier: 'Entry 1',
    shortName: 'rtx2060',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.045,
    fizzGpuPricePerMonth: 32.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 11,
    name: 'NVIDIA RTX 2060 Super',
    tier: 'Entry 1',
    shortName: 'rtx2060super',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.055,
    fizzGpuPricePerMonth: 39.6,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 12,
    name: 'NVIDIA RTX 2070',
    tier: 'Entry 1',
    shortName: 'rtx2070',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 36,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 13,
    name: 'NVIDIA RTX 2080',
    tier: 'Entry 2',
    shortName: 'rtx2080',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 37.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 14,
    name: 'NVIDIA RTX 2080 Super',
    tier: 'Entry 2',
    shortName: 'rtx2080super',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.056,
    fizzGpuPricePerMonth: 40.32,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 15,
    name: 'NVIDIA RTX 3050',
    tier: 'Entry 2',
    shortName: 'rtx3050',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.051,
    fizzGpuPricePerMonth: 36.72,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 16,
    name: 'NVIDIA RTX 3060',
    tier: 'Entry 2',
    shortName: 'rtx3060',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.052,
    fizzGpuPricePerMonth: 37.44,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 17,
    name: 'NVIDIA RTX 3060 Ti',
    tier: 'Entry 2',
    shortName: 'rtx3060ti',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.058,
    fizzGpuPricePerMonth: 41.76,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 18,
    name: 'NVIDIA RTX 3070',
    tier: 'Entry 2',
    shortName: 'rtx3070',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.052,
    fizzGpuPricePerMonth: 37.44,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 19,
    name: 'NVIDIA RTX 3070 Ti',
    tier: 'Entry 2',
    shortName: 'rtx3070ti',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.063,
    fizzGpuPricePerMonth: 45.5,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 20,
    name: 'NVIDIA RTX 4060',
    tier: 'Entry 2',
    shortName: 'rtx4060',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.055,
    fizzGpuPricePerMonth: 39.6,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 21,
    name: 'NVIDIA RTX 4060 Ti',
    tier: 'Entry 2',
    shortName: 'rtx4060ti',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.065,
    fizzGpuPricePerMonth: 46.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 22,
    name: 'NVIDIA RTX 4070',
    tier: 'Entry 2',
    shortName: 'rtx4070',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.058,
    fizzGpuPricePerMonth: 41.76,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 23,
    name: 'NVIDIA Tesla P100 PCIe',
    tier: 'Entry 2',
    shortName: 'p100',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.06,
    fizzGpuPricePerMonth: 43.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 24,
    name: 'NVIDIA RTX A4000',
    tier: 'Entry 2',
    shortName: 'rtxa4000',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.081,
    fizzGpuPricePerMonth: 58.1,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 25,
    name: 'NVIDIA RTX 2080 Ti',
    tier: 'Low 1',
    shortName: 'rtx2080ti',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.07,
    fizzGpuPricePerMonth: 50.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 26,
    name: 'NVIDIA RTX 3080',
    tier: 'Low 1',
    shortName: 'rtx3080',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.07,
    fizzGpuPricePerMonth: 50.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 27,
    name: 'NVIDIA RTX 3080 Ti',
    tier: 'Low 1',
    shortName: 'rtx3080ti',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.072,
    fizzGpuPricePerMonth: 51.84,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 28,
    name: 'NVIDIA RTX 4070 Ti',
    tier: 'Low 1',
    shortName: 'rtx4070ti',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.075,
    fizzGpuPricePerMonth: 54,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 29,
    name: 'NVIDIA RTX 4000',
    tier: 'Low 1',
    shortName: 'rtx4000',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.06,
    fizzGpuPricePerMonth: 43.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 30,
    name: 'NVIDIA P40',
    tier: 'Low 1',
    shortName: 'p40',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.085,
    fizzGpuPricePerMonth: 61.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 31,
    name: 'NVIDIA Tesla T4',
    tier: 'Low 1',
    shortName: 't4',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.035,
    fizzGpuPricePerMonth: 25.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 32,
    name: 'NVIDIA RTX 4080',
    tier: 'Low 2',
    shortName: 'rtx4080',
    multiplier: 0.75,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.085,
    fizzGpuPricePerMonth: 61.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 33,
    name: 'NVIDIA Titan RTX',
    tier: 'Low 2',
    shortName: 'titanrtx',
    multiplier: 0.75,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.132,
    fizzGpuPricePerMonth: 95.05,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 34,
    name: 'NVIDIA RTX 3090',
    tier: 'Low 2',
    shortName: 'rtx3090',
    multiplier: 0.75,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.126,
    fizzGpuPricePerMonth: 90.65,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 35,
    name: 'NVIDIA RTX 3090 Ti',
    tier: 'Low 2',
    shortName: 'rtx3090ti',
    multiplier: 0.75,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.148,
    fizzGpuPricePerMonth: 106.56,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 36,
    name: 'NVIDIA RTX 4090',
    tier: 'Medium 1',
    shortName: 'rtx4090',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.175,
    fizzGpuPricePerMonth: 126,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 37,
    name: 'NVIDIA RTX A5000',
    tier: 'Medium 1',
    shortName: 'rtxa5000',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.088,
    fizzGpuPricePerMonth: 63,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 38,
    name: 'NVIDIA A10',
    tier: 'Medium 1',
    shortName: 'a10',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.091,
    fizzGpuPricePerMonth: 65.45,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 39,
    name: 'NVIDIA A10G',
    tier: 'Medium 1',
    shortName: 'a10g',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.123,
    fizzGpuPricePerMonth: 88.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 40,
    name: 'NVIDIA L4',
    tier: 'Medium 1',
    shortName: 'l4',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.098,
    fizzGpuPricePerMonth: 71.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 41,
    name: 'NVIDIA Tesla V100',
    tier: 'Medium 1',
    shortName: 'v100',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.088,
    fizzGpuPricePerMonth: 63,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 42,
    name: 'NVIDIA A40',
    tier: 'Medium 1',
    shortName: 'a40',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.112,
    fizzGpuPricePerMonth: 79.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 43,
    name: 'NVIDIA L40',
    tier: 'Medium 2',
    shortName: 'l40',
    multiplier: 1.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 44,
    name: 'NVIDIA RTX 8000',
    tier: 'Medium 2',
    shortName: 'rtx8000',
    multiplier: 1.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 45,
    name: 'NVIDIA RTX A6000',
    tier: 'Medium 2',
    shortName: 'rtxa6000',
    multiplier: 1.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 46,
    name: 'NVIDIA L40S',
    tier: 'High 1',
    shortName: 'l40s',
    multiplier: 2,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 47,
    name: 'NVIDIA RTX 6000 Ada',
    tier: 'High 1',
    shortName: 'rtx6000-ada',
    multiplier: 2,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 48,
    name: 'NVIDIA A100 PCIE 40GB',
    tier: 'High 2',
    shortName: 'a100-pcie-40g',
    multiplier: 3,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 49,
    name: 'NVIDIA A100 SXM4 40GB',
    tier: 'High 2',
    shortName: 'a100-sxm-40g',
    multiplier: 3,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 50,
    name: 'NVIDIA A100 80GB',
    tier: 'Ultra High 1',
    shortName: 'a100-80g',
    multiplier: 6,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 51,
    name: 'NVIDIA H100 80G',
    tier: 'Ultra High 2',
    shortName: 'h100',
    multiplier: 12,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0,
    fizzGpuPricePerMonth: 0,
    fizzCpuPricePerMonth: 0,
    fizzRamPricePerGbPerMonth: 0,
    fizzStoragePricePerGbPerMonth: 0,
    vendor: 'nvidia',
  },
  {
    id: 52,
    name: 'NVIDIA GTX 1650',
    tier: 'Entry 1',
    shortName: 'gtx1650',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.04,
    fizzGpuPricePerMonth: 28.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 53,
    name: 'NVIDIA GTX 1660',
    tier: 'Entry 1',
    shortName: 'gtx1660',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.04,
    fizzGpuPricePerMonth: 28.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 54,
    name: 'NVIDIA GTX 1660 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1660ti',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 36,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 55,
    name: 'NVIDIA GTX 1660 Super',
    tier: 'Entry 1',
    shortName: 'gtx1660super',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.055,
    fizzGpuPricePerMonth: 39.6,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 56,
    name: 'NVIDIA RTX 4070 Ti Super',
    tier: 'Low 1',
    shortName: 'rtx4070tisuper',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.078,
    fizzGpuPricePerMonth: 56.16,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 57,
    name: 'NVIDIA RTX 4050',
    tier: 'Entry 2',
    shortName: 'rtx4050',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.055,
    fizzGpuPricePerMonth: 39.6,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 58,
    name: 'NVIDIA GTX 1650 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1650ti',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.05,
    fizzGpuPricePerMonth: 36,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 59,
    name: 'NVIDIA RTX 4000 Ada',
    tier: 'Medium 1',
    shortName: 'rtx4000-ada',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.14,
    fizzGpuPricePerMonth: 100.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 60,
    name: 'NVIDIA RTX 2050',
    tier: 'Entry 1',
    shortName: 'rtx2050',
    multiplier: 0.1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.042,
    fizzGpuPricePerMonth: 30.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 61,
    name: 'NVIDIA Tesla V100S',
    tier: 'Medium 1',
    shortName: 'v100s',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.092,
    fizzGpuPricePerMonth: 66.24,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 62,
    name: 'NVIDIA RTX 3050 Ti',
    tier: 'Entry 2',
    shortName: 'rtx3050ti',
    multiplier: 0.25,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.055,
    fizzGpuPricePerMonth: 39.6,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 63,
    name: 'NVIDIA RTX 4000 SFF Ada',
    tier: 'Medium 1',
    shortName: 'rtx4000-sff-ada',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.145,
    fizzGpuPricePerMonth: 104.4,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 64,
    name: 'NVIDIA RTX 4080 Super',
    tier: 'Low 2',
    shortName: 'rtx4080super',
    multiplier: 0.75,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.09,
    fizzGpuPricePerMonth: 64.8,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 65,
    name: 'NVIDIA RTX 4070 Super',
    tier: 'Low 1',
    shortName: 'rtx4070super',
    multiplier: 0.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.077,
    fizzGpuPricePerMonth: 55.44,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 66,
    name: 'NVIDIA RTX 5090',
    tier: 'Medium 1',
    shortName: 'rtx5090',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.25,
    fizzGpuPricePerMonth: 180,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 67,
    name: 'NVIDIA RTX 5080',
    tier: 'Medium 1',
    shortName: 'rtx5080',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.185,
    fizzGpuPricePerMonth: 133.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 68,
    name: 'NVIDIA RTX 5070 Ti',
    tier: 'Medium 1',
    shortName: 'rtx5070ti',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 69,
    name: 'NVIDIA GH200 96 GB',
    tier: 'Ultra High 2',
    shortName: 'gh200',
    multiplier: 12,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 70,
    name: 'NVIDIA H200 142 GB	',
    tier: 'Ultra High 3',
    shortName: 'h200',
    multiplier: 15,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 71,
    name: 'NVIDIA B200 192 GB',
    tier: 'Ultra High 3',
    shortName: 'b200',
    multiplier: 15,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 72,
    name: 'NVIDIA A30',
    tier: 'Medium 1',
    shortName: 'a30',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 73,
    name: 'NVIDIA A16',
    tier: 'Medium 1',
    shortName: 'a16',
    multiplier: 1,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 74,
    name: 'NVIDIA RTX 6000',
    tier: 'Medium 2',
    shortName: 'rtx6000',
    multiplier: 1.5,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 75,
    name: 'NVIDIA RTX 8000 Ada',
    tier: 'High 1',
    shortName: 'rtx8000-ada',
    multiplier: 2,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.15,
    fizzGpuPricePerMonth: 108,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
  {
    id: 76,
    name: 'NVIDIA RTX 5060 Ti',
    tier: 'Low 2',
    shortName: 'rtx5060ti',
    multiplier: 0.75,
    baseFnPoints: 500,
    fizzGpuPricePerHour: 0.14,
    fizzGpuPricePerMonth: 102.2,
    fizzCpuPricePerMonth: 0.75,
    fizzRamPricePerGbPerMonth: 0.1,
    fizzStoragePricePerGbPerMonth: 0.01,
    vendor: 'nvidia',
  },
];
